### ISSUE TITLE
Sentry consent question won't stop showing up

### ISSUE THREAD

**Issue by juxeii** [matepek/vscode-catch2-test-adapter#189] opened 2020-05-05 20:37 UTC
**Checklist**

- The issue is about this extension and NOT about a fork.
- The latest version of the extension was used.

**Describe the bug**
A notification is shown about `sentry.io`.
No matter what you click here(accept or decline) it will show up again on every project start.

**Screenshots** (optional)
![Notification](https://user-images.githubusercontent.com/4497675/81113481-97662280-8f20-11ea-9432-05fcfa9befdd.JPG)

- Extension Version: 3.0.1
- VS Code Version: 1.44.2
- OS Type and Version: Red Hat

**Comment by matepek** [comment] 2020-05-06 03:40
Hey, 
Well it works for me.
Could you attach the logs? Not just a piece you think it is relevant but the whole from the start until the end.
Just reproduce the issue don't have to run tests, etc... You can mask your personal data if you wish but won't be there much interesting.

**Comment by juxeii** [comment] 2020-05-06 05:35
Here is the for the first startup:

```
[2020-05-06 05:31:08.623] [INFO] {
  uri: h {
    scheme: 'file',
    authority: '',
    path: '/var/fpwork/reiss/gnb/cplane',
    query: '',
    fragment: '',
    _formatted: 'file:///var/fpwork/reiss/gnb/cplane',
    _fsPath: '/var/fpwork/reiss/gnb/cplane'
  },
  name: 'cplane',
  index: 0
} linux v12.4.0 {
  node: '12.4.0',
  v8: '7.4.288.27-node.18',
  uv: '1.29.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.38.0',
  napi: '4',
  llhttp: '1.1.3',
  http_parser: '2.8.0',
  openssl: '1.1.1b',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
} 1.44.2
[2020-05-06 05:31:08.629] [INFO] sentry.io is false
[2020-05-06 05:31:08.638] [INFO] load called
[2020-05-06 05:31:08.639] [INFO] load started
[2020-05-06 05:31:08.640] [INFO] `test.advancedExecutables` is not defined. trying to use `test.executables`
[2020-05-06 05:31:08.641] [INFO] pattern /var/fpwork/reiss/gnb/cplane/build/bin/*UT /var/fpwork/reiss/gnb/cplane {
  isAbsolute: true,
  absPattern: '/var/fpwork/reiss/gnb/cplane/build/bin/*UT',
  isPartOfWs: true,
  relativeToWsPosix: 'build/bin/*UT'
}
[2020-05-06 05:31:08.641] [INFO] Absolute path is used for workspace directory. This is unnecessary, but it should work.
[2020-05-06 05:31:09.054] [INFO] load finished 0
[2020-05-06 05:31:10.352] [INFO] Sentry consent Sure! I love this extension and happy to help.
```
And after restart:

```
[2020-05-06 05:32:42.358] [INFO] {
  uri: h {
    scheme: 'file',
    authority: '',
    path: '/var/fpwork/reiss/gnb/cplane',
    query: '',
    fragment: '',
    _formatted: 'file:///var/fpwork/reiss/gnb/cplane',
    _fsPath: '/var/fpwork/reiss/gnb/cplane'
  },
  name: 'cplane',
  index: 0
} linux v12.4.0 {
  node: '12.4.0',
  v8: '7.4.288.27-node.18',
  uv: '1.29.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.38.0',
  napi: '4',
  llhttp: '1.1.3',
  http_parser: '2.8.0',
  openssl: '1.1.1b',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
} 1.44.2
[2020-05-06 05:32:42.367] [INFO] sentry.io is false
[2020-05-06 05:32:42.380] [INFO] load called
[2020-05-06 05:32:42.381] [INFO] load started
[2020-05-06 05:32:42.382] [INFO] `test.advancedExecutables` is not defined. trying to use `test.executables`
[2020-05-06 05:32:42.384] [INFO] pattern /var/fpwork/reiss/gnb/cplane/build/bin/*UT /var/fpwork/reiss/gnb/cplane {
  isAbsolute: true,
  absPattern: '/var/fpwork/reiss/gnb/cplane/build/bin/*UT',
  isPartOfWs: true,
  relativeToWsPosix: 'build/bin/*UT'
}
[2020-05-06 05:32:42.384] [INFO] Absolute path is used for workspace directory. This is unnecessary, but it should work.
[2020-05-06 05:32:42.760] [INFO] load finished 0
[2020-05-06 05:32:43.861] [INFO] Sentry consent Sure! I love this extension and happy to help.
```
Do you need other logs? How can I change the log level of the extension?

**Comment by matepek** [comment] 2020-05-06 05:49
You cannot change the log level.

That is the end of the log?
The code tries to set the setting and if there is an error it should log it.

Hm.. 

In your user's settings.json (not the one inside the .vscode) you should have `"testMate.cpp.log.logSentry": "enable"`. Can you see that?

**Comment by matepek** [comment] 2020-05-06 05:56
Okay, I have an idea what caused the problem.
I screwed up the migration of this special variable. Do you have a variable in workspace settings.json `catch2TestExplorer.logSentry`?

**Comment by juxeii** [comment] 2020-05-06 05:59
In user settings.json there are these two entries:

> "testMate.cpp.log.userId": "00755c2ff1937ebb49bf9393ac6507d8b7f2c81d",
> "testMate.cpp.log.logSentry": "enable"

Both are "greyed" out saying
`This setting cannot be applied in this window. It will be applied when you open local window.`

**Comment by matepek** [comment] 2020-05-06 06:08
No `catch2TestExplorer `?

Nothing in the workspace or workspaceFolder settings.json?

**Comment by matepek** [comment] 2020-05-06 06:11
Have to ask: Are you familiar with this multi level [vscode settings strucutre](https://code.visualstudio.com/docs/getstarted/settings)?

**Comment by juxeii** [comment] 2020-05-06 06:12
In workspace folder I have
`"testMate.cpp.test.executables": "/var/fpwork/reiss/gnb/cplane/build/bin/*UT"`
I remember that some 2 days ago(or so) I had an entry with `catch2TestExplorer ` for the executables pattern, but that had yellow squiggles and vsc replaced it with the above entry to make setting.json clean again.

**Comment by juxeii** [comment] 2020-05-06 06:17
Yes, I know the hirarchy. What entries do you want?

**Comment by matepek** [comment] 2020-05-06 06:21
I searched for the [error](https://github.com/microsoft/vscode/blob/19c1c8ac0ac6a1805887d3ac3f47b8eef90c9708/src/vs/workbench/contrib/preferences/browser/preferencesRenderers.ts#L1022).

Do you use vscode remote?

**Comment by juxeii** [comment] 2020-05-06 06:28
Yes.

**Comment by matepek** [comment] 2020-05-06 06:33
Well that's a quite important piece of information. I will add this to the issue template. :)

Okay, I see whats the problem here. Hold on..

**Comment by juxeii** [comment] 2020-05-06 06:51
May I ask two more questions:
1) Are variable substitutions supported in executables pattern? E.g. ${env:UT}/somePath/*tests*
2) We have quite a big code base. If I open the extension on the left, it will start search for executables. This takes some minutes. Would it be possible to configure that this will be done automatically after vscode startup?

**Comment by matepek** [comment] 2020-05-06 07:26
Your issue will be fixed in 3.0.2 Thanks for reporting it. (release is done)

Sure, happy to help.

- 1. yes it is. Let me draw your attention to some special variables which will also work:
  - `${osPathSep}`
  - `${osPathEnvSep}`,
  - `${if(iswin)}<W>${else}<U>${endif}`
- 2. Currently: No, it is architectural. But might there is a way. I will check and I will notify you about that.
I guess it spends it's time mainly to list the tests. (with some performance checking it could be verified) If your executables pattern is specific enough that would make a big difference. Because the extension has to test all the matching files event if those are text files. There is some [optimization](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/src/FSWrapper.ts#L85) but specifying the the pattern as strict as possible can make a difference. 


I thought about creating a gitter account might be useful for somebody, but I'm not sure. This extension has so small user base :)

**Comment by juxeii** [comment] 2020-05-06 07:39
1) Ok, will try `os_env` instead of `env`
2) You are right that if I am very specific with the pattern then there is a speedup. But usually I need all tests in the project. And we have lots of them. It would be really helpful if the extension would scan for tests after startup(maybe even create some cache mechanism). Because sometimes I miss to open the extension in the beginning. But right at that point I would need to execute some tests, so I have to wait some minutes before the executables are scanned. Such on optional feature would be greate("Search for executables on startup").

**Comment by matepek** [comment] 2020-05-06 07:44
Well test list caching feature actually exists: `testMate.cpp.discovery.testListCaching`
Let me know the performance of that.

**Comment by juxeii** [comment] 2020-05-06 07:47
Ok, will test that.
Btw: notification problem is fixed, many thx for the fast fix :D

**Comment by matepek** [comment] 2020-05-06 07:48
Thanks to covid :S

**Closed** 2020-05-06 07:48 UTC
Labels: question

**Comment by juxeii** [comment] 2020-05-06 08:11
I think that caching improves the loading time.
Still, an automatic load would be great.

**Comment by matepek** [comment] 2020-05-06 08:11
I found an option.. working on that.

**Comment by matepek** [comment] 2020-05-06 08:20
2 options.. lol One is even better than the other

**Comment by matepek** [comment] 2020-05-06 08:54
Check the last section of the [support](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md) page.

**Comment by matepek** [comment] 2020-05-06 09:28
I also figured out how to run the tests automatically at startup. Description is at [support](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md) page.

**Comment by juxeii** [comment] 2020-05-06 09:36
I added
```
{
            "label": "Activate Test Explorer",
            "command": "${command:test-explorer.reload}", // For running use "${command:test-explorer.run-all}"
            "problemMatcher": [],
            "runOptions": {
                "runOn": "folderOpen" // This will cause the trigger. Have to run manually once!
            }
        }
```
to` tasks.json` but after startup I get
```
Executing task: ${command:test-explorer.reload}  <

The terminal shell path "${command:test-explorer.reload}" does not exist

Terminal will be reused by tasks, press any key to close it.
```

**Comment by matepek** [comment] 2020-05-06 09:54
Can you run it manually? Is that work?

**Comment by juxeii** [comment] 2020-05-06 10:03
Same output when I run it manually.
But it is strange that when I open the extension some minutes after startup, all tests are immedeatly loaded anyway.
That is exactly what I wanted and i could live with this warning ;)

**Comment by matepek** [comment] 2020-05-06 10:06
Using remote right?
I have some ideas. 
Maybe the remote need more time to process all the load events. 
Or maybe it is fast because of the caching?
Is it slow again if you remove the task?
In the first case it is probably vscode or vscode remote related issue.

**Comment by matepek** [comment] 2020-05-06 10:11
There is another way I will release it later but won’t publish officially because this is the nice way. But if you need for workaround we can try that too

**Comment by juxeii** [comment] 2020-05-06 11:28
I disabled caching but it works as expected.
After some time when I open the extension all tests are loaded straight away.
The warning is still there and I cannot even understand how that could possibly work...but it does :)

**Comment by juxeii** [comment] 2020-05-06 11:55
Could it be a problem that I use https://github.com/hbenl/vscode-test-explorer?
I have a different task defined with something like `${command:extension.commandvariable.selectedText`
So I tried to add `extension` after `command` but that did not help.

**Comment by matepek** [comment] 2020-05-06 12:50
Test Explorer is the UI part of of my extension.
No, I suspect its a vscode/vscode-remote issue.
It should be reported.
Meanwhile you can hide the error with this:
```
        {
            "label": "Load TestMate",
            "command": "${command:test-explorer.reload}",
            "problemMatcher": [],
            "runOptions": {
                "runOn": "folderOpen"
            },
            "presentation": {
                "echo": true,
                "reveal": "never",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": false
            }
        }
```

**Comment by juxeii** [comment] 2020-05-08 11:04
See solution here: https://github.com/microsoft/vscode/issues/97119

**Comment by matepek** [comment] 2020-05-08 16:30
Nice, thanks. Updated the doc.
