### ISSUE TITLE
VSC doesn't show all tests in TEST EXPLORER

### ISSUE THREAD

**Issue by VladAdGad** [matepek/vscode-catch2-test-adapter#246] opened 2020-12-12 19:23 UTC
**Checklist**

- [ ] The issue is about this extension and NOT about a fork.
- [ ] The latest version of the extension was used (3.6.15)

**Describe the bug**

I have 23 tests inside my project. But only 12 listed in Test Explorer.

**To Reproduce**

git clone https://github.com/VladAdGad/LeetCode and open in VSC. With Catch2 plugin
conan install .. inside build folder -> cmake configure -> cmake build -> you can run all 23 tests but only 12 listed

**Screenshots** (optional)

![image](https://user-images.githubusercontent.com/15636176/101992989-2c9b7780-3cb7-11eb-82b3-c5bcf2c818f1.png)

**Desktop**

- Extension Version: 3.6.15
- VS Code Version: 
![image](https://user-images.githubusercontent.com/15636176/101993006-4c32a000-3cb7-11eb-861f-df58cfae01cf.png)
- Catch2: 3.0.0
- OS Type and Version: Windows 10 Pro
- Using remote-ssh/docker/wsl?: no

- Last extension version in which the feature were working:

**Log** (optional but recommended)

testMate.cpp.log.logpanel: true where to put this exactly? Link to https://github.com/matepek/vscode-catch2-test-adaapter/blob/master/documents/support.md#getting-logs broken

**Comment by matt-deboer** [comment] 2020-12-12 21:55
Are you using latest Catch2 (v3?) 
If so, this may be a duplicate of #245 (PR: #247 ).

**Comment by VladAdGad** [comment] 2020-12-12 23:39
Yes, 3.0.0

**Comment by matepek** [comment] 2020-12-14 11:35
Hello,
Let us know if the latest version haven't fixed it.

**Closed by matepek** 2020-12-14 11:35 UTC
