### ISSUE TITLE
@doc filter doesn't work

### ISSUE THREAD

**Issue by stefanhaller** [matepek/vscode-catch2-test-adapter#299] opened 2021-11-22 19:27 UTC
**Describe the bug**

- Set the test filter to "Show in Active File Only" (this adds `@doc` to the filter string)
- Expected: see the tests of the currently open source file
- Actual: no tests are shown

**Desktop**

- Extension Version: 4.0.1
- VS Code Version: 1.63.0-insider
- OS Type and Version: macOS 11.6.1
- Using remote-ssh/docker/wsl?: no

**Regression bug?**

Sort of; in the legacy version it works correctly (using the `"testExplorer.useNativeTesting": true` setting).

**Log** (optional but recommended)

Let me know if you'd like me to attach a log.

**Comment by matepek** [comment] 2021-11-22 19:33
I cannot reproduce. in `Version: 1.62.3` Would you try that?

**Comment by stefanhaller** [comment] 2021-11-22 21:22
I see the same behavior in 1.62.3; no tests are displayed when I filter by "@doc".

The command "Test: Run tests in current file" doesn't work either, I wonder if this is related.

What other information can I provide to help track this down?

**Comment by matepek** [comment] 2021-11-22 21:36
What is the output if you run your doctest fro command line?
`./doctest1.exe --list-test-cases --reporters=xml --no-skip=true --no-color=true`

**Comment by stefanhaller** [comment] 2021-11-23 07:52
Found it: my build system is set up to cd into the build folder, which means that I'm getting file paths similar to `<workspace>/build/../src/file.cpp`.

The following patch fixes it for me for google test, but I'm sure there are more places where path.normalize needs to be added:

```
diff --git a/src/framework/GoogleTestExecutable.ts b/src/framework/GoogleTestExecutable.ts
index cd282d4..e278ac6 100644
--- a/src/framework/GoogleTestExecutable.ts
+++ b/src/framework/GoogleTestExecutable.ts
@@ -2,6 +2,7 @@ import * as fs from 'fs';
 import * as vscode from 'vscode';
 import { promisify } from 'util';
 import * as ansi from 'ansi-colors';
+import * as path from 'path';
 
 import { AbstractExecutable as AbstractExecutable, HandleProcessResult } from '../AbstractExecutable';
 import { GoogleTestTest } from './GoogleTestTest';
@@ -323,7 +324,7 @@ class TestSuiteListingProcessor implements XmlTagProcessor {
         this.create(
           tag.attribs.name,
           this.suiteName!,
-          tag.attribs.file,
+          path.normalize(tag.attribs.file),
           tag.attribs.line,
           tag.attribs.type_param,
           tag.attribs.value_param,
```

This also fixes a lot of other problems, BTW; as already mentioned, the command "Test: Run tests in current file" didn't work, and there were no gutter decorations in editor windows.

**Comment by matepek** [comment] 2021-11-23 08:12
Nice work! Thank You

Will be fixed in version 4.0.3+

**Closed by matepek** 2021-11-23 08:12 UTC

**Comment by stefanhaller** [comment] 2021-11-23 08:57
Thanks for the quick fix. I confirm that it works for both googletest and catch2 now.

**Comment by matepek** [comment] 2021-11-23 09:52
Thanks for searching the root cause :)

**Comment by stefanhaller** [comment] 2021-11-23 10:50
Ah, but we have the same problem for catch sections; these still don't show up when filtering by `@doc`. Putting a `path.normalize` in `getOrCreateSubTest` (or the `SubTest` constructor) fixes this, but I'll let you figure out the best place to add it. :-)

**Comment by matepek** [comment] 2021-11-23 11:17
much obliged :)
Will be released soon.
