### ISSUE TITLE
fail to loading testing binary

### ISSUE THREAD

**Issue by iambingoNJU** [matepek/vscode-catch2-test-adapter#420] opened 2024-01-22 02:25 UTC
![image](https://github.com/matepek/vscode-catch2-test-adapter/assets/15451671/55b7dd20-4dcf-4f8e-a882-979f9f00542b)

Where is the log output of this plugin, I can't find any log about this plugin.

And no test case is shown in `TESTING` colume. It seems `TestMate C++` is disabled.

**Comment by iambingoNJU** [comment] 2024-01-22 02:28
I have [Cmake Tools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools) extension installed.

**Comment by iambingoNJU** [comment] 2024-01-22 02:30
And my test binary is on `build` directory and has `test` keyword.

**Comment by geertj** [comment] 2024-01-31 19:56
I have the same issue. This appears to be a regression in v4.8.0. In v4.7.0, my test binaries are correctly scanned and show up in the test explorer. In v4.8.0 they do not show up. I also use CMake Tools, but I am not sure it is related.

Per the changelog, files matching files.watcherExclude are ignored in v4.8.0. I removed my build/ directory (which contains my test binaries) from the ignore list, and this did not make a difference, even after reloading.

**Comment by ryanjmulder** [comment] 2024-02-06 20:11
I also have this issue. From the logs, it seems that 4.8.0 never transitions into the "Checking file for tests: " log statements.

Here's the not working log from 4.8.0
```
[2024-02-06 20:02:45.194] [INFO] 8
[2024-02-06 20:02:45.194] [INFO] `test.advancedExecutables` is not defined. trying to use `test.executables`
[2024-02-06 20:02:45.195] [DEBUG] ExecutableConfig.resolveVariable:  {
  value: '{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*',
  resolved: Promise { <pending> },
  strictAllowed: false
}
[2024-02-06 20:02:45.196] [INFO] pattern {build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}* /home/rmulder/devel/MonitoringController/monitoring-controller/tests {
  isAbsolute: false,
  absPath: '/home/rmulder/devel/MonitoringController/monitoring-controller/tests/{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*',
  isPartOfWs: true,
  relativeToWsPosix: '{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*'
}
```

Here's the working log from 4.7.0
```
[2024-02-06 20:05:58.310] [INFO] 8
[2024-02-06 20:05:58.310] [INFO] `test.advancedExecutables` is not defined. trying to use `test.executables`
[2024-02-06 20:05:58.311] [DEBUG] ExecutableConfig.resolveVariable:  {
  value: '{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*',
  resolved: Promise { <pending> },
  strictAllowed: false
}
[2024-02-06 20:05:58.312] [INFO] pattern {build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}* /home/rmulder/devel/MonitoringController/monitoring-controller/tests {
  isAbsolute: false,
  absPath: '/home/rmulder/devel/MonitoringController/monitoring-controller/tests/{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*',
  isPartOfWs: true,
  relativeToWsPosix: '{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*'
}
[2024-02-06 20:05:58.331] [DEBUG] Checking file for tests: ... 
{and many more lines like this}
```

**Comment by matepek** [comment] 2024-02-07 05:12
Please follow the instructions in [template](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/.github/ISSUE_TEMPLATE/bug_report.md?plain=1)

**Comment by matepek** [comment] 2024-02-07 06:12
Released a new version with improved logging. I bet your issue is related to the `files.watcherExclude` config which is respected since `v4.8.0`. 

I'm closing this in faith that I'm right and the issue can be easily solved but let me know if I'm wrong and we can investigate further. Also let me know if changing that config makes your workflow uncomfortable in soma way.
Bests,

**Closed by matepek** 2024-02-07 06:12 UTC

**Comment by geertj** [comment] 2024-02-12 22:22
@matepek I did some more investigation. It appears that there are actually two settings: `files.watcherExclude` and `files.exclude`. On 4.7.0, both appear to be ignored. However, in 4.8.0 both settings must not contain a pattern that excludes the executable. If I remove the exclusion in both places, the tests show up.

In the typical CMake use case, you have a "build" directory that contains your build artifacts including generated build-system files, object files and test binaries. A subset of these files can subsequently be installed, which typically does not include the test executables. Normally you don't want the "build" directory to show up in VSCode as they are all temporary files, but you do want VSCode to load your tests from there.

Any thoughts on how to best achieve this?
