### ISSUE TITLE
Tests marked may_fail etc. are shown as failed (red cross)

### ISSUE THREAD

**Issue by bilderbuchi** [matepek/vscode-catch2-test-adapter#283] opened 2021-09-09 14:57 UTC
I am running test cases with doctest that are [marked](https://github.com/onqtam/doctest/blob/master/doc/markdown/testcases.md#decorators) `may_fail`, `should_fail` or `expected_failures`. The asserts within those tests fail, but the test is considered passed due to the decorator. (There is an equivalent feature in Catch called ["tags"](https://github.com/catchorg/Catch2/blob/devel/docs/test-cases-and-sections.md#special-tags))
In the Test UI, such tests are shown/considered as failed (red cross), when they should be considered as successful (green check).
Ideally, this would show some third status indicating that such a decorator was in play (yellow check?), but I don't know if this is supported upstream.

See for example these doctest tests:
```
TEST_CASE("expected failures" * doctest::expected_failures(1))
{
   REQUIRE(false);
}
TEST_CASE("may fail" * doctest::may_fail())
{
   REQUIRE(false);
}
TEST_CASE("should fail" * doctest::should_fail())
{
   REQUIRE(false);
}
```
The output of running such tests in the command line shows the following summary:
```
[doctest] test cases: 3 | 3 passed | 0 failed | 26 skipped
[doctest] assertions: 3 | 0 passed | 3 failed |
[doctest] Status: SUCCESS!
```
but in the Test UI I only get red checkmarks:
![grafik](https://user-images.githubusercontent.com/327442/132709774-93198fbb-b5bd-4bc0-a8bb-615c50a41709.png)

- Extension Version:
- VS Code Version: 1.60.0
- Catch2 / Google Test / DOCTest Version: doctest 2.4.6
- OS Type and Version: Windows 10
- Using remote-ssh/docker/wsl?: no
- I don't think that this situtation has been considered so far, so I didn't think a log would be that useful.

**Comment by matepek** [comment] 2021-09-10 17:58
Fixed in 3.6.31

**Closed by matepek** 2021-09-10 17:58 UTC

**Comment by matepek** [comment] 2021-09-10 18:23
By the way, this is a bit controversial 
```
TEST_CASE("test mix: should_fail & expected_failures(1): false" * doctest::should_fail() * doctest::expected_failures(1)) { CHECK(false); }
```
because it is interpreted as passed by doctest

**Comment by bilderbuchi** [comment] 2021-09-10 19:37
Wow, thanks, that was quick!

Hm, I haven't yet considered composing those decorators, but it makes sense to me. Both decorators individually would pass the test (yes, the Check fails, and it should; yes, we have 1 expected failure). Or are you talking about the test adapter/UI behaviour being wrong?

**Comment by bilderbuchi** [comment] 2021-09-29 11:25
@matepek are you considering decorators in general? I have a test in my suite that is marked with `doctest::skip()`, but when I "Run all the tests", this test also is run. Is that something I should write a bug report for`, or is the problem on my end somehow?

**Comment by matepek** [comment] 2021-09-29 16:49
The problem is that doctest does not tell us if a test is marked as skipped at enumeration stage: 
`./doctest1.exe --reporters=xml --list-test-cases --no-skip=true`

Well it could be solved with enumerating the tests twice but I'm not really fond of that idea. Would you open an issue in doctest and ask them to add a xml attribute for the TestCase in case it's skipped?

**Comment by matepek** [comment] 2021-09-30 09:28
Ah, I've totally forgot about it. :)

**Comment by bilderbuchi** [comment] 2021-12-03 09:59
Should I open a separate ticket here so that we don't forget to add the skip treatment when this is implemented upstream?

**Comment by matepek** [comment] 2021-12-03 14:14
Would you be that kind.

Also it would be great if a doctest issue was opened about reporting the result of SubCases. Don't know the result of them.

**Comment by bilderbuchi** [comment] 2021-12-03 15:44
Part 1 done in #309. 

I'm not familiar with the subcase thing, what is this about? Could you maybe create a separate one yourself? Considering https://github.com/doctest/doctest/issues/554, though, it's questionable how much dev work will happen over at doctest in the future...

**Comment by onqtam** [comment] 2021-12-09 17:56
@matepek 

> Would you be that kind.
> 
> Also it would be great if a doctest issue was opened about reporting the result of SubCases. Don't know the result of them.

Hmmm, subcases are just `{}` blocks after `if()` statements generated from the macros - no return code, and there's no counting & reporting of failed assertions in subcases.
