### ISSUE TITLE
Add action to list and execute sub cases individually, just like test cases

### ISSUE THREAD

**Issue by yudi-azvd** [matepek/vscode-catch2-test-adapter#269] opened 2021-06-07 22:08 UTC
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
When using `SUBCASE` from **doctest**, the Test Explorer only lists the test cases, but not the sub cases individually. Besides that
if a subcase fails the test, the entire test case fails. To debug the failing subcase I can set a breakpoint inside the method
`parser.runOn()` (see the picture below), but the debugger will stop at the breakpoint in all subcases instead of just stopping at the failing subcase. It's actually running all sub cases in the test case.

![image](https://user-images.githubusercontent.com/37981839/121093459-71661e00-c7c3-11eb-8509-d3db1d1f64f3.png)

I've tried setting the breakpoint in the subcase and when the debugger stopped I would go to the body of the method and then re enable the breakpoints inside it. It works, but well... it's not optimal.

**Describe the solution you'd like**
It would be very nice if the extension could list and run each **sub case** individually just like with test cases. And have these buttons as well
![image](https://user-images.githubusercontent.com/37981839/121093354-4f6c9b80-c7c3-11eb-9726-f083b72888f7.png)

### Note
I think doctest can't list sub cases with `-sc` right now. I mean, it should because it is described in the docs. But I can't get that to work. I think it's a bug so I opened the a [issue](https://github.com/onqtam/doctest/issues/513) there some days ago. Just something to keep in mind if you decide solve this issue :)

**Edit**: added link to mentioned issue.

**Comment by yudi-azvd** [comment] 2021-07-16 20:53
Ok... after some experimentation I realized that `-sc` only filters subcases. Test cases which do not include the filtered subcase will still be executed.

So to run a specific subcase, and **only this subcase** one would have to filter the test case containing the subcase and the subcase, like so:
    
    ./unit-tests -tc=instructions* -sc=add-instruction

Instead of running:

    ./unit-tests -sc=add-instruction    

At least that was I what I understood.

**Comment by Trass3r** [comment] 2021-08-05 18:12
Related to / potential duplicate of #66.
The frameworks simply don't offer a way to list all the subcases.

**Comment by matepek** [comment] 2021-11-22 18:16
Dear User(s),

Version 4+ has been release. Hoping it makes this issue resolved.
If you disagree then please comment `!open`.

doctest has some limitation so hard to evaluate the result of a sub-case.

**Closed by matepek** 2021-11-22 18:16 UTC
Labels: enhancement, v4.x

**Comment by yudi-azvd** [comment] 2021-12-02 23:08
Well, i think it's missing the debug button.

Another thing. What happened to these buttons?
![image](https://user-images.githubusercontent.com/37981839/144517383-a4bd8e82-926c-4bae-a1f9-f0fc1be50f47.png)

(run, debug, etc...)

**Comment by matepek** [comment] 2021-12-02 23:11
Thats a feature request. On the list but will take a while. 

Regarding to the other changes. 
VSCode is responsible for the UI and control, this extension just fills with items.

**Comment by yudi-azvd** [comment] 2021-12-02 23:30
> Thats a feature request. On the list but will take a while.

got it

> Regarding to the other changes.
> VSCode is responsible for the UI and control, this extension just fills with items.

not got it. Why the don't appear anymore? Can I tell vscode to make those buttons appear? If yes, how?

**Comment by matepek** [comment] 2021-12-03 08:06
One of the changes from v3.x -> v4.y is that [Test Explorer API](https://github.com/hbenl/vscode-test-adapter-api)
has been replaced with [native API](https://code.visualstudio.com/api/extension-guides/testing).
(With this we get rid of some limitation.)
Both APIs allow us to add tests and the API triggers this extension to run tests. So the user interface and most of the control code is not part of this extension.

Feel free to open an issue on [their github](https://github.com/microsoft/vscode/issues).
You can make an example with this extension but bare in mind that they are supporting several other test provider(likeg this extension) and the are looking for general solutions

**Comment by Trass3r** [comment] 2021-12-03 09:53
https://github.com/microsoft/vscode/issues/133338

**Comment by yudi-azvd** [comment] 2021-12-03 17:42
ok, I get it now. Thanks for the explanation
