### ISSUE TITLE
Debugger fails to start when environment variables contain newlines

### ISSUE THREAD

**Issue by bspeice** [matepek/vscode-catch2-test-adapter#364] opened 2022-10-22 00:52 UTC
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

Please see also https://github.com/microsoft/vscode-cmake-tools/issues/2686

Environment variables with newlines in them cause problems for the Microsoft GDB adapter (screenshot attached, please also see microsoft/vscode-cmake-tools#2442 and microsoft/vscode-cmake-tools#2515).

**To Reproduce**

Attempt to debug a test using the gutter "play" button in an environment where environment variables contain newlines. In my project fork, I've included a [devcontainer setup](https://github.com/bspeice/vscode-catch2-test-adapter/tree/filter_envvar_newline_test) that can be used to reliably reproduce the problem (specifically, the `environment-modules` package sets up some functions that get exported with newlines).

**Screenshots** (optional)

![Screenshot from 2022-10-21 20-42-54](https://user-images.githubusercontent.com/1199853/197308966-4993ef8e-e7e1-42ae-b3f1-0212842d2849.png)

**Desktop**

- Extension Version: 4.3.1
- VS Code Version: 1.70.2
- Catch2 / Google Test / DOCTest Version: GTest a9b2f0495
- OS Type and Version: Linux (Debian Bullseye)
- Using remote-ssh/docker/wsl?: Docker - devcontainer

**Log** (optional but recommended)

Log not included, will file a pull request momentarily.

**Comment by matepek** [comment] 2022-10-22 04:30
Hello,

It sounds like a "Microsoft GDB adapter" issue.
Why do you think it should be fixed here?

**Comment by matepek** [comment] 2022-10-22 05:01
Btw you can check the documentation of [debugConfigTemplate](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/debug.configTemplate.md)

And I added a new paragraph which might be helpful for this case to [here](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#i-have-environment-variable-with-new-line-character-which-causes-debugging-issue)

**Comment by bspeice** [comment] 2022-10-23 20:05
> Hello,
> 
> It sounds like a "Microsoft GDB adapter" issue. Why do you think it should be fixed here?

Because other official C++ plugins have fixed the issue without touching the cpptools extension (https://github.com/microsoft/vscode-cmake-tools/pull/2518). I agree that it's an issue with the cppdbg adapter (the lldb extension adapter doesn't suffer the same problem), but I'm hoping to merge this fix as a way to improve the default user experience.

I'm currently trying to investigate how VS Code launches GDB (I _think_ the cpptools extension is responsible for actually spawning the executable), I'll add another comment once I have more details on whether this can be solved upstream. My concern is that GDB commands in general don't support newline characters (https://github.com/microsoft/vscode-cpptools/issues/3666) so there might not be a general solution.

> Btw you can check the documentation of [debugConfigTemplate](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/debug.configTemplate.md)
> 
> And I added a new paragraph which might be helpful for this case to [here](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#i-have-environment-variable-with-new-line-character-which-causes-debugging-issue)

That works if users are aware of all environment variables that contain newlines ahead of time. As is the case with the `environment-modules` package, it's very frequently the case that users never _intended_ to have environment variables with newlines (some distros install it by default), but ended up with problems anyway.

My specific concern is that error messages are extremely difficult to understand and it's not clear how to fix the problems. If you're not comfortable filtering out environment variables, would it be beneficial to have some form of warning (popup notification that can be ignored in the future?) so users are aware of the potential problems?

**Comment by bspeice** [comment] 2022-10-23 21:02
I was wrong about the extension; the specific problem comes from the debug engine that cpptools relies on not escaping commands properly:

https://github.com/microsoft/MIEngine/blob/3511d551feb27fd5e5d78e0edd98ce6ff827384b/src/MICore/Debugger.cs#L840

I _think_ the fix might be to add `\n` to the debug escape sequences here:

https://github.com/microsoft/MIEngine/blob/3511d551feb27fd5e5d78e0edd98ce6ff827384b/src/MICore/Debugger.cs#L774

Going to open an issue there to see what they think.

**Comment by matepek** [comment] 2022-10-24 03:36
If it were "fixed" in this extension then maybe one day another user came and say "my multiline env variables are not working, the extension is buggy". Should I say: "It's not a bug, it's a feature"?
:)
Beside jokes. If we agree that the issue is coming from another extension and I provided a way for workaround I think I will close this.

**Closed by matepek** 2022-10-24 03:36 UTC
