### ISSUE TITLE
Logging with log.logpanel settings doesn't work

### ISSUE THREAD

**Issue by vakokako** [matepek/vscode-catch2-test-adapter#382] opened 2023-04-17 10:00 UTC
**Describe the bug**

Neither of the following logging settings work:
```json
"testMate.cpp.log.logpanel": true,
"testMate.cpp.log.logfile": "/tmp/testMate.log",
```
The "/tmp/testMate.log" isn't created and I don't see any output in the log panel.

**Comment by emmenlau** [comment] 2023-04-17 10:11
Oh yes, this is also a problem for me. I do not see any logging, not with these settings and also not in the output window.

**Comment by matepek** [comment] 2023-04-18 05:48
Well I cannot reproduce.

Btw, one has to reload vscode after changing those flags.

**Comment by matepek** [comment] 2023-04-18 06:02
I'm closing this. if the restart doesn't solve feel free to create a new issue according to the description

**Closed by matepek** 2023-04-18 06:02 UTC
Labels: invalid

**Comment by vakokako** [comment] 2023-04-18 12:22
After reloading logging still doesn't work.
